title: My first blog
author: iamjayeshsingh
email: iamjayeshsingh@domain.com
theme : minima
description: > # this means to ignore newlines until "baseurl:"
  My first blog

# social links
twitter_username: iamjayeshsingh
github_username:  iamjayeshsingh

show_excerpts: true # set to false to remove excerpts on the homepage
